# Generated by Django 5.2.6 on 2025-09-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_status_options_alter_type_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='ddsrecord',
            options={'ordering': ['-date_created'], 'verbose_name': 'Запись ДДС', 'verbose_name_plural': 'Записи ДДС'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name'], 'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
    ]
