# Generated by Django 5.2.6 on 2025-09-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_options_alter_ddsrecord_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ddsrecord',
            index=models.Index(fields=['date_created'], name='main_ddsrec_date_cr_052127_idx'),
        ),
        migrations.AddIndex(
            model_name='ddsrecord',
            index=models.Index(fields=['status'], name='main_ddsrec_status__2573e2_idx'),
        ),
        migrations.AddIndex(
            model_name='ddsrecord',
            index=models.Index(fields=['type'], name='main_ddsrec_type_id_f448f8_idx'),
        ),
        migrations.AddIndex(
            model_name='ddsrecord',
            index=models.Index(fields=['category'], name='main_ddsrec_categor_220b64_idx'),
        ),
        migrations.AddIndex(
            model_name='ddsrecord',
            index=models.Index(fields=['sub_category'], name='main_ddsrec_sub_cat_99be1a_idx'),
        ),
    ]
